import { Component, HTMLAttributes, Props, ReactNode, ReactElement, ComponentClass, StatelessComponent } from 'react';

declare type ReactComponent<P> = string | ComponentClass<P> | StatelessComponent<P>;

export function hh(component: ReactComponent<any>): (selector?: any, properties?: any, ...children: ReactNode[]) => ReactElement<any>;

export function h(component: ReactComponent<any>, ...children: ReactNode[]): ReactElement<any>;
export function h(component: ReactComponent<any>, selector: string, ...children: ReactNode[]): ReactElement<any>;
export function h<P>(component: ReactComponent<P>, selector: string, properties: P & Props<any>, ...children: ReactNode[]): ReactElement<any>;
export function h<P>(component: ReactComponent<P>, properties: P & Props<any>, ...children: ReactNode[]): ReactElement<any>;

export function a(...children: ReactNode[]): ReactElement<any>;
export function a(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function a(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function a(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function abbr(...children: ReactNode[]): ReactElement<any>;
export function abbr(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function abbr(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function abbr(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function address(...children: ReactNode[]): ReactElement<any>;
export function address(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function address(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function address(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function area(...children: ReactNode[]): ReactElement<any>;
export function area(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function area(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function area(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function article(...children: ReactNode[]): ReactElement<any>;
export function article(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function article(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function article(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function aside(...children: ReactNode[]): ReactElement<any>;
export function aside(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function aside(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function aside(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function audio(...children: ReactNode[]): ReactElement<any>;
export function audio(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function audio(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function audio(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function b(...children: ReactNode[]): ReactElement<any>;
export function b(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function b(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function b(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function base(...children: ReactNode[]): ReactElement<any>;
export function base(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function base(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function base(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function bdi(...children: ReactNode[]): ReactElement<any>;
export function bdi(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function bdi(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function bdi(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function bdo(...children: ReactNode[]): ReactElement<any>;
export function bdo(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function bdo(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function bdo(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function big(...children: ReactNode[]): ReactElement<any>;
export function big(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function big(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function big(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function blockquote(...children: ReactNode[]): ReactElement<any>;
export function blockquote(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function blockquote(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function blockquote(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function body(...children: ReactNode[]): ReactElement<any>;
export function body(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function body(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function body(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function br(...children: ReactNode[]): ReactElement<any>;
export function br(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function br(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function br(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function button(...children: ReactNode[]): ReactElement<any>;
export function button(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function button(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function button(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function canvas(...children: ReactNode[]): ReactElement<any>;
export function canvas(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function canvas(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function canvas(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function caption(...children: ReactNode[]): ReactElement<any>;
export function caption(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function caption(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function caption(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function cite(...children: ReactNode[]): ReactElement<any>;
export function cite(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function cite(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function cite(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function code(...children: ReactNode[]): ReactElement<any>;
export function code(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function code(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function code(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function col(...children: ReactNode[]): ReactElement<any>;
export function col(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function col(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function col(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function colgroup(...children: ReactNode[]): ReactElement<any>;
export function colgroup(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function colgroup(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function colgroup(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function data(...children: ReactNode[]): ReactElement<any>;
export function data(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function data(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function data(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function datalist(...children: ReactNode[]): ReactElement<any>;
export function datalist(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function datalist(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function datalist(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function dd(...children: ReactNode[]): ReactElement<any>;
export function dd(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function dd(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function dd(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function del(...children: ReactNode[]): ReactElement<any>;
export function del(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function del(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function del(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function details(...children: ReactNode[]): ReactElement<any>;
export function details(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function details(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function details(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function dfn(...children: ReactNode[]): ReactElement<any>;
export function dfn(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function dfn(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function dfn(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function dialog(...children: ReactNode[]): ReactElement<any>;
export function dialog(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function dialog(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function dialog(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function div(...children: ReactNode[]): ReactElement<any>;
export function div(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function div(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function div(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function dl(...children: ReactNode[]): ReactElement<any>;
export function dl(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function dl(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function dl(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function dt(...children: ReactNode[]): ReactElement<any>;
export function dt(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function dt(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function dt(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function em(...children: ReactNode[]): ReactElement<any>;
export function em(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function em(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function em(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function embed(...children: ReactNode[]): ReactElement<any>;
export function embed(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function embed(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function embed(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function fieldset(...children: ReactNode[]): ReactElement<any>;
export function fieldset(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function fieldset(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function fieldset(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function figcaption(...children: ReactNode[]): ReactElement<any>;
export function figcaption(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function figcaption(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function figcaption(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function figure(...children: ReactNode[]): ReactElement<any>;
export function figure(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function figure(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function figure(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function footer(...children: ReactNode[]): ReactElement<any>;
export function footer(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function footer(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function footer(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function form(...children: ReactNode[]): ReactElement<any>;
export function form(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function form(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function form(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function h1(...children: ReactNode[]): ReactElement<any>;
export function h1(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function h1(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function h1(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function h2(...children: ReactNode[]): ReactElement<any>;
export function h2(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function h2(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function h2(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function h3(...children: ReactNode[]): ReactElement<any>;
export function h3(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function h3(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function h3(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function h4(...children: ReactNode[]): ReactElement<any>;
export function h4(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function h4(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function h4(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function h5(...children: ReactNode[]): ReactElement<any>;
export function h5(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function h5(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function h5(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function h6(...children: ReactNode[]): ReactElement<any>;
export function h6(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function h6(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function h6(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function head(...children: ReactNode[]): ReactElement<any>;
export function head(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function head(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function head(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function header(...children: ReactNode[]): ReactElement<any>;
export function header(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function header(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function header(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function hgroup(...children: ReactNode[]): ReactElement<any>;
export function hgroup(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function hgroup(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function hgroup(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function hr(...children: ReactNode[]): ReactElement<any>;
export function hr(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function hr(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function hr(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function html(...children: ReactNode[]): ReactElement<any>;
export function html(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function html(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function html(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function i(...children: ReactNode[]): ReactElement<any>;
export function i(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function i(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function i(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function iframe(...children: ReactNode[]): ReactElement<any>;
export function iframe(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function iframe(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function iframe(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function img(...children: ReactNode[]): ReactElement<any>;
export function img(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function img(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function img(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function input(...children: ReactNode[]): ReactElement<any>;
export function input(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function input(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function input(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function ins(...children: ReactNode[]): ReactElement<any>;
export function ins(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function ins(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function ins(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function kbd(...children: ReactNode[]): ReactElement<any>;
export function kbd(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function kbd(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function kbd(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function keygen(...children: ReactNode[]): ReactElement<any>;
export function keygen(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function keygen(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function keygen(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function label(...children: ReactNode[]): ReactElement<any>;
export function label(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function label(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function label(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function legend(...children: ReactNode[]): ReactElement<any>;
export function legend(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function legend(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function legend(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function li(...children: ReactNode[]): ReactElement<any>;
export function li(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function li(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function li(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function link(...children: ReactNode[]): ReactElement<any>;
export function link(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function link(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function link(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function main(...children: ReactNode[]): ReactElement<any>;
export function main(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function main(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function main(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function map(...children: ReactNode[]): ReactElement<any>;
export function map(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function map(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function map(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function mark(...children: ReactNode[]): ReactElement<any>;
export function mark(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function mark(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function mark(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function menu(...children: ReactNode[]): ReactElement<any>;
export function menu(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function menu(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function menu(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function menuitem(...children: ReactNode[]): ReactElement<any>;
export function menuitem(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function menuitem(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function menuitem(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function meta(...children: ReactNode[]): ReactElement<any>;
export function meta(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function meta(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function meta(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function meter(...children: ReactNode[]): ReactElement<any>;
export function meter(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function meter(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function meter(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function nav(...children: ReactNode[]): ReactElement<any>;
export function nav(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function nav(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function nav(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function noscript(...children: ReactNode[]): ReactElement<any>;
export function noscript(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function noscript(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function noscript(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function object(...children: ReactNode[]): ReactElement<any>;
export function object(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function object(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function object(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function ol(...children: ReactNode[]): ReactElement<any>;
export function ol(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function ol(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function ol(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function optgroup(...children: ReactNode[]): ReactElement<any>;
export function optgroup(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function optgroup(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function optgroup(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function option(...children: ReactNode[]): ReactElement<any>;
export function option(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function option(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function option(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function output(...children: ReactNode[]): ReactElement<any>;
export function output(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function output(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function output(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function p(...children: ReactNode[]): ReactElement<any>;
export function p(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function p(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function p(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function param(...children: ReactNode[]): ReactElement<any>;
export function param(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function param(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function param(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function picture(...children: ReactNode[]): ReactElement<any>;
export function picture(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function picture(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function picture(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function pre(...children: ReactNode[]): ReactElement<any>;
export function pre(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function pre(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function pre(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function progress(...children: ReactNode[]): ReactElement<any>;
export function progress(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function progress(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function progress(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function q(...children: ReactNode[]): ReactElement<any>;
export function q(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function q(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function q(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function rp(...children: ReactNode[]): ReactElement<any>;
export function rp(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function rp(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function rp(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function rt(...children: ReactNode[]): ReactElement<any>;
export function rt(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function rt(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function rt(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function ruby(...children: ReactNode[]): ReactElement<any>;
export function ruby(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function ruby(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function ruby(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function s(...children: ReactNode[]): ReactElement<any>;
export function s(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function s(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function s(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function samp(...children: ReactNode[]): ReactElement<any>;
export function samp(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function samp(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function samp(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function script(...children: ReactNode[]): ReactElement<any>;
export function script(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function script(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function script(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function section(...children: ReactNode[]): ReactElement<any>;
export function section(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function section(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function section(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function select(...children: ReactNode[]): ReactElement<any>;
export function select(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function select(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function select(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function small(...children: ReactNode[]): ReactElement<any>;
export function small(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function small(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function small(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function source(...children: ReactNode[]): ReactElement<any>;
export function source(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function source(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function source(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function span(...children: ReactNode[]): ReactElement<any>;
export function span(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function span(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function span(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function strong(...children: ReactNode[]): ReactElement<any>;
export function strong(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function strong(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function strong(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function style(...children: ReactNode[]): ReactElement<any>;
export function style(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function style(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function style(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function sub(...children: ReactNode[]): ReactElement<any>;
export function sub(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function sub(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function sub(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function summary(...children: ReactNode[]): ReactElement<any>;
export function summary(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function summary(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function summary(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function sup(...children: ReactNode[]): ReactElement<any>;
export function sup(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function sup(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function sup(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function table(...children: ReactNode[]): ReactElement<any>;
export function table(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function table(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function table(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function tbody(...children: ReactNode[]): ReactElement<any>;
export function tbody(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function tbody(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function tbody(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function td(...children: ReactNode[]): ReactElement<any>;
export function td(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function td(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function td(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function textarea(...children: ReactNode[]): ReactElement<any>;
export function textarea(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function textarea(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function textarea(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function tfoot(...children: ReactNode[]): ReactElement<any>;
export function tfoot(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function tfoot(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function tfoot(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function th(...children: ReactNode[]): ReactElement<any>;
export function th(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function th(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function th(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function thead(...children: ReactNode[]): ReactElement<any>;
export function thead(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function thead(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function thead(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function time(...children: ReactNode[]): ReactElement<any>;
export function time(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function time(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function time(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function title(...children: ReactNode[]): ReactElement<any>;
export function title(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function title(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function title(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function tr(...children: ReactNode[]): ReactElement<any>;
export function tr(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function tr(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function tr(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function track(...children: ReactNode[]): ReactElement<any>;
export function track(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function track(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function track(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function u(...children: ReactNode[]): ReactElement<any>;
export function u(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function u(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function u(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function ul(...children: ReactNode[]): ReactElement<any>;
export function ul(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function ul(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function ul(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function video(...children: ReactNode[]): ReactElement<any>;
export function video(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function video(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function video(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function wbr(...children: ReactNode[]): ReactElement<any>;
export function wbr(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function wbr(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function wbr(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function circle(...children: ReactNode[]): ReactElement<any>;
export function circle(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function circle(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function circle(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function clipPath(...children: ReactNode[]): ReactElement<any>;
export function clipPath(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function clipPath(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function clipPath(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function defs(...children: ReactNode[]): ReactElement<any>;
export function defs(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function defs(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function defs(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function ellipse(...children: ReactNode[]): ReactElement<any>;
export function ellipse(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function ellipse(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function ellipse(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function g(...children: ReactNode[]): ReactElement<any>;
export function g(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function g(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function g(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function image(...children: ReactNode[]): ReactElement<any>;
export function image(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function image(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function image(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function line(...children: ReactNode[]): ReactElement<any>;
export function line(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function line(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function line(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function linearGradient(...children: ReactNode[]): ReactElement<any>;
export function linearGradient(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function linearGradient(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function linearGradient(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function mask(...children: ReactNode[]): ReactElement<any>;
export function mask(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function mask(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function mask(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function path(...children: ReactNode[]): ReactElement<any>;
export function path(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function path(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function path(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function pattern(...children: ReactNode[]): ReactElement<any>;
export function pattern(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function pattern(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function pattern(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function polygon(...children: ReactNode[]): ReactElement<any>;
export function polygon(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function polygon(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function polygon(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function polyline(...children: ReactNode[]): ReactElement<any>;
export function polyline(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function polyline(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function polyline(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function radialGradient(...children: ReactNode[]): ReactElement<any>;
export function radialGradient(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function radialGradient(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function radialGradient(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function rect(...children: ReactNode[]): ReactElement<any>;
export function rect(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function rect(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function rect(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function stop(...children: ReactNode[]): ReactElement<any>;
export function stop(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function stop(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function stop(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function svg(...children: ReactNode[]): ReactElement<any>;
export function svg(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function svg(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function svg(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function text(...children: ReactNode[]): ReactElement<any>;
export function text(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function text(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function text(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function tspan(...children: ReactNode[]): ReactElement<any>;
export function tspan(selector: string, ...children: ReactNode[]): ReactElement<any>;
export function tspan(selector: string, properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;
export function tspan(properties: HTMLAttributes<any>, ...children: ReactNode[]): ReactElement<any>;